// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigdalApi.Data;

#nullable disable

namespace MigdalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MigdalApi.Models.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodMiktzoa")
                        .HasColumnType("int");

                    b.Property<int>("CodSugMosach")
                        .HasColumnType("int");

                    b.Property<string>("Ktovet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenahelMiktzoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miktzoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mikud")
                        .HasColumnType("int");

                    b.Property<int>("MisparMosach")
                        .HasColumnType("int");

                    b.Property<long>("RashamHavarot")
                        .HasColumnType("bigint");

                    b.Property<string>("ShemMosach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SugMosach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Testime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yishuv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Garages");
                });
#pragma warning restore 612, 618
        }
    }
}
